version: '2'
services:
  db:
    image: mysql:5.6.23
    env_file:
      - local.env
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - local.env
